name: GithubAction

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests and generate report
        run: npm test

      - name: Upload screenshots and videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports/mochawesome
